### 넘파이(numpy)
다차원 배열(행렬)을 쉽게 처리하고 효율적으로 사용할 수 있도록 지원하는 파이썬 라이브러리<br>
수치 해석, 통계 관련 기능을 구현할 때 기본이 되는 모듈임<br>
Numerical Python의 줄임말임

In [34]:
import numpy as np

# 파이썬의 range()
# list(range(15))

# 넘파이의 arange()
x = np.arange(15)
print(x)
print(x.shape)

x2 = x.reshape(3,5)
print(x)
print(x2)
print(x2[1:, ::2])

x2[1:, ::2] = -99
print(x2)

print(x2.max())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 5  7  9]
 [10 12 14]]
[[  0   1   2   3   4]
 [-99   6 -99   8 -99]
 [-99  11 -99  13 -99]]
13


In [42]:
# 넘파이 - array() : 리스트 생성
a = [3, 1, 2]
x = np.array([3, 1, 2])
print(x)
print(type(x))
print(x.shape)

x2 = np.array([[1, 2, 3], [4, 5, 6]])
print(x2)
print(x2.shape)

[3 1 2]
<class 'numpy.ndarray'>
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [44]:
# numpy 연산
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x + y)

[3. 6. 9.]


In [50]:
a = np.nan
print(a)
print(type(a))

a2 = np.zeros((3, 3))
print(a2)

a3 = np.ones((2, 3))
print(a3)

nan
<class 'float'>
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
